#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/settings.php';

use Symfony\Component\Console\Application;
use Maestro\Commands\InstallCommand;
use Maestro\Commands\UpdateCommand;

$app = new Application();

$app->add(new InstallCommand($settings));
$app->add(new UpdateCommand($settings));

$app->run();