#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Maestro\Commands\InstallCommand;

$app = new Application();

$app->add(new InstallCommand());

$app->run();